/// Every icon webkit95 shows, as original pixel art in the Win95 palette. Views render these at
/// integer scale with nearest neighbor sampling.
public enum Icon: String, CaseIterable, Sendable {
    // 16x16 and 32x32 app icon
    case app16, app32
    // 20x20 toolbar icons
    case back, forward, stop, refresh, home, search, favorites, print, font, assistant
    // 32x32 message box icons
    case info, warning, question, error
    // 16x16 small icons
    case folder, page, document, globe, lock, zone, tool, thought, favoriteItem
    // title bar button glyphs, black on the button face
    case minimize, maximize, restore, close
    // menu, scrollbar and control glyphs
    case check, radio, submenuArrow, arrowUp, arrowDown, arrowLeft, arrowRight, comboArrow
    case expandPlus, expandMinus

    public var art: PixelArt { Icons.art[self] ?? Icons.missing }
}

public enum Icons {
    static let missing = PixelArt([
        "kkkkkkkk",
        "krrrrrrk",
        "krrrrrrk",
        "kkkkkkkk",
    ])

    /// Frames of the toolbar logo animation. Frame 0 is the resting frame.
    public static let logoFrames: [PixelArt] = [logo0, logo1, logo2, logo3, logo4, logo5, logo6, logo7]

    static let art: [Icon: PixelArt] = [
        .app16: app16,
        .app32: app32,
        .back: back,
        .forward: forward,
        .stop: stop,
        .refresh: refresh,
        .home: home,
        .search: search,
        .favorites: favorites,
        .print: print,
        .font: font,
        .assistant: assistant,
        .info: info,
        .warning: warning,
        .question: question,
        .error: error,
        .folder: folder,
        .page: page,
        .document: document,
        .globe: globe,
        .lock: lock,
        .zone: zone,
        .tool: tool,
        .thought: thought,
        .favoriteItem: favoriteItem,
        .minimize: minimize,
        .maximize: maximize,
        .restore: restore,
        .close: close,
        .check: check,
        .radio: radio,
        .submenuArrow: submenuArrow,
        .arrowUp: arrowUp,
        .arrowDown: arrowDown,
        .arrowLeft: arrowLeft,
        .arrowRight: arrowRight,
        .comboArrow: comboArrow,
        .expandPlus: expandPlus,
        .expandMinus: expandMinus,
    ]

    static let app16 = PixelArt([
        ".............k..",
        "............kyk.",
        "...........kywyk",
        ".....kkkkkk.kyk.",
        "....kLcttttknkn.",
        "...kLLLLttttk.nn",
        "...ktLLLGtttk.nn",
        "...ktttGGtttk.n.",
        ".nnkttttGGttnnn.",
        ".n.ktttttttnn...",
        "nn.ktttttnnnk...",
        "nn..kGnnnntk....",
        ".nnnnnnkkkk.....",
        "................",
        "................",
        "................",
    ])

    static let app32 = PixelArt([
        "................................",
        "...........................k....",
        "..........................kyk...",
        ".........................kyyyk..",
        "........................kyywyyk.",
        ".............kkkkkk......kyyyk..",
        "..........kkkttttttkkk....kyk...",
        ".........kcccttttttttGk....k....",
        "........kcLccttttttttttknnnn....",
        ".......kcLLLLLLtttttttttk..nnn..",
        "......kcLLLLLLLttttttttttk...nn.",
        "......kLcLLLLLLLLttttttttk....n.",
        "......kttLLLLLLLLGtttttttk....n.",
        ".....ktttLLLLLLLGGtttttGttk..nn.",
        ".....kttttLLLLLGGGtttttGGGk.nn..",
        ".....kttttttttGGGGGtttttGGknn...",
        "....nkttttttttttGGGtttttGGnn....",
        "...nnkttttttttttttGGttttGnn.....",
        "..nn.ktttttttttttttGtttnnnk.....",
        ".nn...kttttttttttttttnnntk......",
        ".n....kttttttttttttnnntttk......",
        ".n....kGGttttttttnnntttttk......",
        ".nn....kGGttttnnnnttttttk.......",
        "..nnn...knnnnnnttttttttk........",
        "....nnnnnnGGttttttttttk.........",
        "..........kkkttttttkkk..........",
        ".............kkkkkk.............",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
    ])

    static let back = PixelArt([
        "....................",
        ".........k..........",
        "........kkg.........",
        ".......kLkg.........",
        "......kLGkg.........",
        ".....kLGGkg.........",
        "....kLGGGLkkkkkkkk..",
        "...kLGGGGGLLLLLLLkg.",
        "..kLGGGGGGGGGGGGGkg.",
        ".kLGGGGGGGGGGGGGGkg.",
        "..kLGGGGGGGGGGGGGkg.",
        "...kLGGGGGGGGGGGGkg.",
        "....kLGGGGkkkkkkkkg.",
        ".....kLGGkggggggggg.",
        "......kLGkg.........",
        ".......kLkg.........",
        "........kkg.........",
        ".........kg.........",
        "..........g.........",
        "....................",
    ])

    static let forward = PixelArt([
        "....................",
        "..........k.........",
        "..........kk........",
        "..........kLk.......",
        "..........kLLk......",
        "..........kLGLk.....",
        "..kkkkkkkkLGGGLk....",
        "..kLLLLLLLGGGGGLk...",
        "..kLGGGGGGGGGGGGLk..",
        "..kLGGGGGGGGGGGGGLk.",
        "..kLGGGGGGGGGGGGGkgg",
        "..kLGGGGGGGGGGGGkgg.",
        "..kkkkkkkkLGGGGkgg..",
        "...gggggggkLGGkgg...",
        "..........kLGkgg....",
        "..........kLkgg.....",
        "..........kkgg......",
        "..........kgg.......",
        "...........g........",
        "....................",
    ])

    static let stop = PixelArt([
        ".....kkkkkkkk.......",
        "....krrrrrrrmk......",
        "...krrrrrrrrrmk.....",
        "..krrrrrrrrrrrmk....",
        ".krrrwrrrrrrrwrmk...",
        "krrrwwwrrrrrwwwrmk..",
        "krrrrwwwrrrwwwrrmkg.",
        "krrrrrwwwrwwwrrrmkg.",
        "krrrrrrwwwwwrrrrmkg.",
        "krrrrrrrwwwrrrrrmkg.",
        "krrrrrrwwwwwrrrrmkg.",
        "krrrrrwwwrwwwrrrmkg.",
        "kmrrrwwwrrrwwwrrmkg.",
        ".kmrwwwrrrrrwwwmkgg.",
        "..kmrwrrrrrrrwmkgg..",
        "...kmrrrrrrrrmkgg...",
        "....kmmmmmmmmkgg....",
        ".....kkkkkkkkgg.....",
        "......gggggggg......",
        "....................",
    ])

    static let refresh = PixelArt([
        "....................",
        ".......kkkkkk.......",
        ".....kkkLLLLkkk.....",
        "....kkLLGGGGLLkk....",
        "...kkLGGGGGGGGLkk...",
        "..kkkkkkkkkkkLGLkk..",
        "............kkLGLk..",
        "...kk........kkLGkk.",
        "..kkkk........kLGLk.",
        ".kkcckk.....kkkLGGkk",
        "kkcbbkkk.....kkLGkk.",
        ".kcbbk........kkkk..",
        ".kkcbkk........kk...",
        "..kcbckk............",
        "..kkcbckkkkkkkkkkk..",
        "...kkcbcccccccckk...",
        "....kkcbbbbbbbkk....",
        ".....kkkcbbbkkk.....",
        ".......kkkkkk.......",
        "....................",
    ])

    static let home = PixelArt([
        ".........k..........",
        "........kmk..kkk....",
        ".......krrmk.krk....",
        "......krrrrmkkrk....",
        ".....krrrrrrmkrk....",
        "....krrrrrrrrmkk....",
        "...krrrrrrrrrrmk....",
        "..krrrrrrrrrrrrmk...",
        ".kmmmmmmmmmmmmmmmk..",
        "kkkkkkkkkkkkkkkkkkk.",
        "...kwwwwwwwwwwwwkg..",
        "...kwiiiiikkkkkskg..",
        "...kwkkkkikckckskg..",
        "...kwkrrkikkkkkskg..",
        "...kwkrmkikccckskg..",
        "...kwkrykikkkkkskg..",
        "...kwkrmkiiiiiiskg..",
        "...kwkrmkssssssskg..",
        "...kkkkkkkkkkkkkkg..",
        "....gggggggggggggg..",
    ])

    static let search = PixelArt([
        "....................",
        ".....kkkkkk.........",
        "...kkwwwwwwkk.......",
        "..kwwsnnnnswwk......",
        "..kwnnLLbbnngk......",
        ".kwsnLwLLGbnswk.....",
        ".kwnbwLLGGbbngk.....",
        ".kwnbbbbbGGbngk.....",
        ".kwnbbbbbbGnngk.....",
        ".kwnbbbbbbbnngk.....",
        ".kwsnGbbbbnnsgk.....",
        "..kwnnGbnnnngk......",
        "..kwgsnnnnsggkk.....",
        "...kkwgggggkkmrk....",
        ".....kkkkkk.krmrk...",
        ".............krmrk..",
        "..............krmrk.",
        "...............krmk.",
        "................kkk.",
        "....................",
    ])

    static let favorites = PixelArt([
        ".........k..........",
        ".........kg.........",
        ".........kg.........",
        "........kwk.........",
        "........kwkg........",
        "........kwkg........",
        ".......kwywk........",
        "kkkkkkkwyyywkkkkkkk.",
        ".kwwwwwyyyyywwwwwkgg",
        "..kkwyyyyyyyyyokkgg.",
        "...gkwyyyyyyyokggg..",
        ".....kwyyyyyokgg....",
        ".....kwyyyyyokg.....",
        ".....kwyoooyokg.....",
        ".....kwokkkwokg.....",
        "....kwokgggkwwk.....",
        "....kwkgg...kwkg....",
        "....kkgg.....kkg....",
        ".....gg.......gg....",
        "....................",
    ])

    static let print = PixelArt([
        "....................",
        ".....kkkkkkkkkk.....",
        ".....kwwwwwwwwk.....",
        ".....kwggggggwk.....",
        ".....kwwwwwwwwk.....",
        ".....kwgggggwwk.....",
        ".....kwwwwwwwwk.....",
        "...kkkkkkkkkkkkkk...",
        "..kwwwwwwwwwwwwwwk..",
        ".kkkkkkkkkkkkkkkkkk.",
        ".kwwwwwwwwwwwwwwwwkg",
        ".kwsssssssssssssLgkg",
        ".kwskkkkkkkkkkkksgkg",
        ".kwssssssssssssssgkg",
        ".kwssssssssssssssgkg",
        ".kwgkkkkkkkkkkkkggkg",
        ".kkkkwggggggwwwkkkkg",
        "..ggkwwwwwwwwwwkgggg",
        "....kkkkkkkkkkkk....",
        "....................",
    ])

    static let font = PixelArt([
        "....................",
        "....................",
        "....................",
        "......nn............",
        ".....nnnn...........",
        ".....nnnn...........",
        "....nn.nnn..........",
        "....nn.nnn..........",
        "...nn...nnn.........",
        "...nn...nnn.........",
        "..nnnnnnnnnn........",
        "..nn.....nnn...nnn..",
        ".nn.......nnn....nn.",
        ".nn.......nnn..nnnn.",
        "nn.........nnnnn.nn.",
        "nn.........nnnnn.nn.",
        "nnnn.....nnnnn.nnnnn",
        "....................",
        "....................",
        "....................",
    ])

    static let assistant = PixelArt([
        "................k...",
        "...............kyk..",
        "..............kyyyk.",
        ".............kyywyyk",
        "..............kyyyk.",
        "...kkkkkkkkkkk.kyk..",
        "..kwwwwwwwwwwlk.k...",
        ".kwwwwwwwwwwwwlk....",
        ".kwwwwwwwwwwwwlkg...",
        ".kwwnnwnnwnnwwlkg...",
        ".kwwnnwnnwnnwwlkg...",
        ".kwwwwwwwwwwwwlkg...",
        ".klwwwwwwwwwwwlkg...",
        "..klwwllllllllkgg...",
        "...kwlkkkkkkkkgg....",
        "...klkggggggggg.....",
        "...kkgg.............",
        "...kgg..............",
        "....g...............",
        "....................",
    ])

    static let info = PixelArt([
        "................................",
        "...........kkkkkkkk.............",
        "........kkkwwwwwwwlkkk..........",
        ".......kwwwwwwwwwwwwwlk.........",
        "......kwwwwwwwbbbwwwwwlk........",
        ".....kwwwwwwwwbbbwwwwwwlk.......",
        "....kwwwwwwwwwbbbwwwwwwwlk......",
        "....kwwwwwwwwwwwwwwwwwwwlkg.....",
        "...kwwwwwwwwwwwwwwwwwwwwwlkg....",
        "...kwwwwwwwwbbbbbwwwwwwwwlkg....",
        "...kwwwwwwwwwwbbbwwwwwwwwlkgg...",
        "..kwwwwwwwwwwwbbbwwwwwwwwwlkg...",
        "..kwwwwwwwwwwwbbbwwwwwwwwwlkg...",
        "..kwwwwwwwwwwwbbbwwwwwwwwwlkgg..",
        "..kwwwwwwwwwwwbbbwwwwwwwwwlkgg..",
        "..klwwwwwwwwwwbbbwwwwwwwwwlkgg..",
        "...kwwwwwwwwwwbbbwwwwwwwwlkggg..",
        "...kwwwwwwwwbbbbbbbwwwwwwlkggg..",
        "...klwwwwwwwwwwwwwwwwwwwwlkgg...",
        "....kwwwwwwwwwwwwwwwwwwwlkggg...",
        "....klwwwwwwwwwwwwwwwwwwlkggg...",
        ".....klwwwwwwwwwwwwwwwwlkggg....",
        "......kwwwwwwwwwwwwwwwlkgggg....",
        "......kwwwwwwwwwwwwlllkgggg.....",
        ".....kwwwwwllllllllkkkgggg......",
        ".....kwwwwlkkkkkkkkgggggg.......",
        ".....kwwllkggggggggggggg........",
        ".....kllkkggggggggggg...........",
        ".....kkkggggg...................",
        ".....k.ggggg....................",
        ".......ggg......................",
        ".......g........................",
    ])

    static let warning = PixelArt([
        "................................",
        "...............k................",
        "...............k................",
        "..............kokg..............",
        ".............kyyok..............",
        ".............kyyokg.............",
        "............kyyyyokg............",
        "............kyyyyokg............",
        "...........kyyyyyyokg...........",
        "...........kyyyyyyokg...........",
        "..........kyyykkkyyokg..........",
        "..........kyykkkkkyokg..........",
        ".........kyyykkkkkyyokg.........",
        ".........kyyykkkkkyyokg.........",
        "........kyyyyykkkyyyyokg........",
        "........kyyyyykkkyyyyokg........",
        ".......kyyyyyykkkyyyyyokg.......",
        "......kyyyyyyyykyyyyyyyok.......",
        "......kyyyyyyyykyyyyyyyokg......",
        ".....kyyyyyyyyyyyyyyyyyyokg.....",
        ".....kyyyyyyyykkkyyyyyyyokg.....",
        "....kyyyyyyyyykkkyyyyyyyyokg....",
        "....kyyyyyyyyykkkyyyyyyyyokg....",
        "...kyyyyyyyyyyyyyyyyyyyyyyokg...",
        "...kyyyyyyyyyyyyyyyyyyyyyyokg...",
        "..kyyyyyyyyyyyyyyyyyyyyyyyyokg..",
        "..kyyyyyyyyyyyyyyyyyyyyyyyyokg..",
        ".koooooooooooooooooooooooooookg.",
        "kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.",
        "...ggggggggggggggggggggggggggggg",
        "..gggggggggggggggggggggggggggggg",
        "................................",
    ])

    static let question = PixelArt([
        "................................",
        "...........kkkkkkkk.............",
        "........kkkwwwwwwwlkkk..........",
        ".......kwwwwwwwwwwwwwlk.........",
        "......kwwwwwwbbbbbwwwwlk........",
        ".....kwwwwwwbbbbbbbwwwwlk.......",
        "....kwwwwwwbbbwwwbbbwwwwlk......",
        "....kwwwwwwbbbwwwbbbwwwwlkg.....",
        "...kwwwwwwwwwwwwwbbbwwwwwlkg....",
        "...kwwwwwwwwwwwwbbbwwwwwwlkg....",
        "...kwwwwwwwwwwwbbbwwwwwwwlkgg...",
        "..kwwwwwwwwwwwbbbwwwwwwwwwlkg...",
        "..kwwwwwwwwwwwbbbwwwwwwwwwlkg...",
        "..kwwwwwwwwwwwbbbwwwwwwwwwlkgg..",
        "..kwwwwwwwwwwwwwwwwwwwwwwwlkgg..",
        "..klwwwwwwwwwwbbbwwwwwwwwwlkgg..",
        "...kwwwwwwwwwwbbbwwwwwwwwlkggg..",
        "...kwwwwwwwwwwbbbwwwwwwwwlkggg..",
        "...klwwwwwwwwwwwwwwwwwwwwlkgg...",
        "....kwwwwwwwwwwwwwwwwwwwlkggg...",
        "....klwwwwwwwwwwwwwwwwwwlkggg...",
        ".....klwwwwwwwwwwwwwwwwlkggg....",
        "......kwwwwwwwwwwwwwwwlkgggg....",
        "......kwwwwwwwwwwwwlllkgggg.....",
        ".....kwwwwwllllllllkkkgggg......",
        ".....kwwwwlkkkkkkkkgggggg.......",
        ".....kwwllkggggggggggggg........",
        ".....kllkkggggggggggg...........",
        ".....kkkggggg...................",
        ".....k.ggggg....................",
        ".......ggg......................",
        ".......g........................",
    ])

    static let error = PixelArt([
        "................................",
        "...........kkkkkkkk.............",
        "........kkkrrrrrrrmkkk..........",
        ".......krrrrrrrrrrrrrmk.........",
        ".....kkrrrrrrrrrrrrrrrmkk.......",
        "....krrrrrrrrrrrrrrrrrrrmk......",
        "....krrrrrrrrrrrrrrrrrrrmkg.....",
        "...krrrrrrrrrrrrrrrrrrrrrmkg....",
        "..krrrrrrwwrrrrrrrrwwrrrrrmk....",
        "..krrrrrwwwwrrrrrrwwwwrrrrmkg...",
        "..krrrrrwwwwwrrrrwwwwwrrrrmkgg..",
        ".krrrrrrrwwwwwrrwwwwwrrrrrrmkg..",
        ".krrrrrrrrwwwwwwwwwwrrrrrrrmkg..",
        ".krrrrrrrrrwwwwwwwwrrrrrrrrmkgg.",
        ".krrrrrrrrrrwwwwwwrrrrrrrrrmkgg.",
        ".krrrrrrrrrrwwwwwwrrrrrrrrrmkgg.",
        ".krrrrrrrrrwwwwwwwwrrrrrrrrmkgg.",
        ".krrrrrrrrwwwwwwwwwwrrrrrrrmkgg.",
        ".kmrrrrrrwwwwwrrwwwwwrrrrrrmkgg.",
        "..krrrrrwwwwwrrrrwwwwwrrrrmkggg.",
        "..krrrrrwwwwrrrrrrwwwwrrrrmkggg.",
        "..kmrrrrrwwrrrrrrrrwwrrrrrmkgg..",
        "...kmrrrrrrrrrrrrrrrrrrrrmkggg..",
        "....krrrrrrrrrrrrrrrrrrrmkgggg..",
        "....kmmrrrrrrrrrrrrrrrrmmkggg...",
        ".....kkmrrrrrrrrrrrrrrmkkggg....",
        "......gkmmmrrrrrrrrmmmkggggg....",
        ".......gkkkmmmmmmmmkkkggggg.....",
        ".........ggkkkkkkkkgggggg.......",
        "..........gggggggggggggg........",
        ".............gggggggg...........",
        "................................",
    ])

    static let folder = PixelArt([
        "................",
        "................",
        ".kkkkkk.........",
        "kyyyyyykkkkkkkk.",
        "kyoooooyyyyyyyk.",
        "kkkkkkkkkkkkkkk.",
        "kwwwwwwwwwwwwwk.",
        "kwyyyyyyyyyyyok.",
        "kwyyyyyyyyyyyok.",
        "kwyyyyyyyyyyyok.",
        "kwyyyyyyyyyyyok.",
        "kwyyyyyyyyyyyok.",
        "kwooooooooooook.",
        "kkkkkkkkkkkkkkk.",
        "................",
        "................",
    ])

    static let page = PixelArt([
        "..kkkkkkkk......",
        "..kwwwwwwkk.....",
        "..kwwwwwwklk....",
        "..kwwwwwwkllk...",
        "..kwwwwwwkkkkk..",
        "..kwwwwwwwwwwkg.",
        "..kwggggggwwwkg.",
        "..kwwwwwwwwwwkg.",
        "..kwgggggggwwkg.",
        "..kwwwwwwwwwwkg.",
        "..kwggggggggwkg.",
        "..kwwwwwwwwwwkg.",
        "..kwgggggwwwwkg.",
        "..kwwwwwwwwwwkg.",
        "..kkkkkkkkkkkkg.",
        "...gggggggggggg.",
    ])

    static let document = PixelArt([
        "..kkkkkkkkkk....",
        "..knnnnnnnnkk...",
        "..knwwwwnnnklk..",
        "..knnnnnnnnkkkk.",
        "..kwwwwwwwwwwwkg",
        "..kwbbbbbbbbwwkg",
        "..kwwwwwwwwwwwkg",
        "..kwbbbbbbbbbwkg",
        "..kwwwwwwwwwwwkg",
        "..kwbbbbbbbwwwkg",
        "..kwwwwwwwwwwwkg",
        "..kwbbbbbbbbbwkg",
        "..kwwwwwwwwwwwkg",
        "..kwbbbbbwwwwwkg",
        "..kkkkkkkkkkkkkg",
        "...gggggggggggg.",
    ])

    static let globe = PixelArt([
        "................",
        "....kkkkkkkk....",
        "...kccbbbbbbk...",
        "..kcLLLLLbbbbk..",
        ".kccLLLLLGbbbbk.",
        ".kLcbLLLLGGbbbk.",
        ".kbbbbLLGGGbbbk.",
        ".kbbbbbbbbGGbbk.",
        ".kbbbbbbbbbGbnk.",
        ".kbbbbbbbbbbnnk.",
        ".kbbbbbbbbbbnnk.",
        ".kGGbbbbbbbnnnk.",
        "..kGGGbbbnnnnk..",
        "...kbGbnnnnnk...",
        "....kkkkkkkk....",
        "................",
    ])

    static let lock = PixelArt([
        "................",
        ".....kkkkkk.....",
        "....kwwwwwgk....",
        "....kwkkkkgk....",
        "....kwk..kgk....",
        "....kwk..kgk....",
        "...kkkkkkkkkk...",
        "...kwwwwwwwwk...",
        "...kwyyyyyyok...",
        "...kwyykkyyok...",
        "...kwykkkkyok...",
        "...kwykkkkyok...",
        "...kwyykkyyok...",
        "...kwyykkyyok...",
        "...kooooooook...",
        "...kkkkkkkkkk...",
    ])

    static let zone = PixelArt([
        "...........g....",
        ".....kkkkk.gg...",
        "....kcbbbGk.gg..",
        "...kLcbbbbbk.gg.",
        "..kLLLbbbbbbk.g.",
        "..kLLLLbbbbbk.g.",
        "..kbbLGbbbGGk.g.",
        "..kbbbGGbbGGk.g.",
        "..kbbbbbbbnGk.g.",
        "...kbbbbbnnk.gg.",
        "....kbbnnnk.gg..",
        ".....kkkkk.gg...",
        ".......kk.gg....",
        ".....gggggg.....",
        "...kkkkkkkkkk...",
        "................",
    ])

    static let tool = PixelArt([
        "................",
        ".........kkkk...",
        "........kwwk....",
        ".......kwgk...k.",
        ".......kwk...kk.",
        ".......kwk..kwk.",
        ".......kwwkkwgk.",
        "......kwsgwwgk..",
        ".....kwsgkkkk...",
        "....kwsgk.......",
        "...kwsgk........",
        "..kwsgk.........",
        ".kwsgk..........",
        ".kwgk...........",
        ".kkk............",
        "................",
    ])

    static let thought = PixelArt([
        "................",
        ".....kkkkkk.....",
        "....kwwwwwwk....",
        "...kwyyyyyywk...",
        "...kwyyyyyyok...",
        "...kwyyyyyyok...",
        "...kwyyyyyyok...",
        "...kwyyyyyyok...",
        "...kwyyyyyyok...",
        "....kwyyyyok....",
        ".....kwoook.....",
        ".....kkkkkk.....",
        ".....kwwwwk.....",
        ".....kggggk.....",
        ".....kkkkkk.....",
        ".......kk.......",
    ])

    static let favoriteItem = PixelArt([
        "..kkkkkkkk......",
        "..kwwwwwwkk.....",
        "..kwwwwwwklk....",
        "..kwwwwwwkllk...",
        "..kwwwwwwkkkkk..",
        "..kwwwwwwwwwwkg.",
        "..kwgkggggwwwkg.",
        "..kwkokwwwwwwkg.",
        "..kkyokkgggwwkg.",
        ".kyyyyyokwwwwkg.",
        ".koyyyyokgggwkg.",
        "..kyyyokwwwwwkg.",
        "..kyoookgwwwwkg.",
        "..kokkookwwwwkg.",
        "..kkkkkkkkkkkkg.",
        "...gggggggggggg.",
    ])

    static let minimize = PixelArt([
        "........",
        "........",
        "........",
        "........",
        "........",
        ".kkkkkk.",
        ".kkkkkk.",
    ])

    static let maximize = PixelArt([
        "kkkkkkkkk",
        "kkkkkkkkk",
        "k.......k",
        "k.......k",
        "k.......k",
        "k.......k",
        "k.......k",
        "k.......k",
        "kkkkkkkkk",
    ])

    static let restore = PixelArt([
        "..kkkkkk",
        "..kkkkkk",
        "..k....k",
        "kkkkkk.k",
        "kkkkkk.k",
        "k....kkk",
        "k....k..",
        "k....k..",
        "kkkkkk..",
    ])

    static let close = PixelArt([
        "kk....kk",
        ".kk..kk.",
        "..kkkk..",
        "...kk...",
        "..kkkk..",
        ".kk..kk.",
        "kk....kk",
    ])

    static let check = PixelArt([
        "......k",
        ".....kk",
        "k...kkk",
        "kk.kkk.",
        "kkkkk..",
        ".kkk...",
        "..k....",
    ])

    static let radio = PixelArt([
        ".kkkk.",
        "kkkkkk",
        "kkkkkk",
        "kkkkkk",
        "kkkkkk",
        ".kkkk.",
    ])

    static let submenuArrow = PixelArt([
        "k...",
        "kk..",
        "kkk.",
        "kkkk",
        "kkk.",
        "kk..",
        "k...",
    ])

    static let arrowUp = PixelArt([
        "...k...",
        "..kkk..",
        ".kkkkk.",
        "kkkkkkk",
    ])

    static let arrowDown = PixelArt([
        "kkkkkkk",
        ".kkkkk.",
        "..kkk..",
        "...k...",
    ])

    static let arrowLeft = PixelArt([
        "...k",
        "..kk",
        ".kkk",
        "kkkk",
        ".kkk",
        "..kk",
        "...k",
    ])

    static let arrowRight = PixelArt([
        "k...",
        "kk..",
        "kkk.",
        "kkkk",
        "kkk.",
        "kk..",
        "k...",
    ])

    static let comboArrow = PixelArt([
        "kkkkkkk",
        ".kkkkk.",
        "..kkk..",
        "...k...",
    ])

    static let expandPlus = PixelArt([
        "ggggggggg",
        "gwwwwwwwg",
        "gwwwkwwwg",
        "gwwwkwwwg",
        "gwkkkkkwg",
        "gwwwkwwwg",
        "gwwwkwwwg",
        "gwwwwwwwg",
        "ggggggggg",
    ])

    static let expandMinus = PixelArt([
        "ggggggggg",
        "gwwwwwwwg",
        "gwwwwwwwg",
        "gwwwwwwwg",
        "gwkkkkkwg",
        "gwwwwwwwg",
        "gwwwwwwwg",
        "gwwwwwwwg",
        "ggggggggg",
    ])

    static let logo0 = PixelArt([
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        ".............kkkkkk.............",
        "...........kkbbbbbbkk...........",
        ".........kkccLLLLLGbbkk.........",
        "........kccccLLLLLGGbbbk....k...",
        "........kccLcbLLLLGGGGbk...kyk..",
        ".......kccLLbbLLLGGGGGbbk.kywyk.",
        ".......kbccbbbbLLGGGGGGbk..kyk..",
        "......kbbbbbbbbbbbbGGGGbnk.ok...",
        "......kbbbbbbbbbbbbbbGGbnkoo....",
        "......kbbbbbbbbbbbbbbbbGnk......",
        "......kbbbbbbbbbbbbbbbbGnk......",
        "......kbbbbbbbbbbbbbbbnnnk......",
        "......kbbbGbbbbbbbbbbbnnnk......",
        ".......kbbGGGGbbbbbbbnnnk.......",
        ".......kbbbGGGbbbbbbnnnnk.......",
        "........kbbGGGGGbbnnnnnk........",
        "........kbbbbbGGbnnnnnnk........",
        ".........kkbbbbnnnnnnkk.........",
        "...........kknnnnnnkk...........",
        ".............kkkkkk.............",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
    ])

    static let logo1 = PixelArt([
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "..........................k.....",
        ".............kkkkkk......kyk....",
        "...........kkbbLLbbkk...kywyk...",
        ".........kkccbLLLLGGGkk..kyko...",
        "........kccccbbLLLGGGGbk..k.....",
        "........kcccLLbbLLGGGGGk........",
        ".......kccccbbbbbGGGGGGGk.......",
        ".......kbccbbbbbbbbbbGGGk.......",
        "......kbbbbbbbbbbbbbbbbGGk......",
        "......kbbbbbbbbbbbbbbbbbGk......",
        "......kLbbbbbbbbbbbbbbbbGk......",
        "......kLbbbbbbbbbbbbbbbnnk......",
        "......kGbbbbGbbbbbbbbbnnnk......",
        "......kGbbbbGGGGbbbbbbnnnk......",
        ".......kGbbbGGGGbbbbbnnnk.......",
        ".......kGbbbbGGGGGbbnnnnk.......",
        "........kGbbbbGGGGnnnnnk........",
        "........kbbbbbbbbnnnnnnk........",
        ".........kkbbbbnnnnnnkk.........",
        "...........kknnnnnnkk...........",
        ".............kkkkkk.............",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
    ])

    static let logo2 = PixelArt([
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        ".............kkkkkk.............",
        "...........kkbbbLLGkk...........",
        ".........kkccbbbLLGGGkk.........",
        "........kccccbLLbbGGGGGk........",
        "........kccccbbLbbbGGGGk........",
        ".......kccccbbbbbbbbbGbGk.......",
        ".......kbccbbbbbbbbbbbbbk.......",
        "......kLbbbbbbbbbbbbbbbbnk......",
        "......kLLbbbbbbbbbbbbbbbnk......",
        "......kLLbbbbbbbbbbbbbbbnk......",
        "......kLLbbbbbGbbbbbbbbnnk......",
        "......kGGbbbbbGGGGbbbbnnnk......",
        "......kGGGbbbbbGGGGbbbnnnk......",
        ".......kbGbbbbbGGGGGbnnnk.......",
        ".......kbbGbbbbGGGGGnnnnk.......",
        "........kbbbbbbbbbnnnnnk........",
        "........kbbbbbbbbnnnnnnk........",
        ".........kkbbbbnnnnnnkk.........",
        "...........kknnnnnnkk...........",
        ".............kkkkkk.............",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
    ])

    static let logo3 = PixelArt([
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        ".............kkkkkk.............",
        "...........kkbbbbLGkk...........",
        ".........kkccbbbLLbGGkk.........",
        "........kccccbbbLLbbGGGk........",
        "........kccccbbbbbbbbbGk........",
        ".......kLcccbbbbbbbbbbbbk.......",
        ".......kLLcbbbbbbbbbbbbbk.......",
        "......kLLLbbbbbbbbbbbbbbnk......",
        "......kLLLLbbbbbbbbbbbbbnk......",
        "......kLLLLbbbbbbbbbbbbbnk......",
        "......kLLLLbbbbbGGGGbbbnnk......",
        "......kbGGGGbbbbbGGGGbnnnk......",
        "......kbbbGGbbbbbGGGGGnnnk......",
        ".......kbbbbGbbbbGGGGGnnk.......",
        ".......kbbbbGbbbbbbbGnnnk.......",
        "........kbbbbbbbbbnnnnnk........",
        "........kbbbbbbbbnnnnnnk........",
        ".........kkbbbbnnnnnnkk.........",
        "...........kknnnnnnkk...........",
        ".............kkkkkk.............",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
    ])

    static let logo4 = PixelArt([
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        ".............kkkkkk.............",
        "...........kkbbbbbbkk...........",
        ".........kkccbbbbbGGbkk.........",
        "........kccccbbbbbbbbbGk........",
        "........kLLccbbbbbbbbbbk........",
        ".......kLLLcbbbbbbbbbbbbk.......",
        ".......kLLLLbbbbbbbbbbbbk.......",
        "......kLLLLLLbbbbbbbbbbbnk......",
        "......kLLLLLLLbbbbbbbbbbnk......",
        "......kLLLLLLLbbbbbGGGbbnk......",
        "......kbbbLLLGbbbbbbGGGnnk......",
        "....ookbbbbGGGGbbbbGGGGnnk......",
        "...ko.kbbbbbbGGbbbbbGGGGnk......",
        "..kyk..kbbbbbbGGbbbbbnGnk.......",
        ".kywyk.kbbbbbbbbbbbbnnnnk.......",
        "..kyk...kbbbbbbbbbnnnnnk........",
        "...k....kbbbbbbbbnnnnnnk........",
        ".........kkbbbbnnnnnnkk.........",
        "...........kknnnnnnkk...........",
        ".............kkkkkk.............",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
    ])

    static let logo5 = PixelArt([
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        ".............kkkkkk.............",
        "...........kkbbbbbbkk...........",
        ".........kkccbbbbbbbGkk.........",
        "........kcLccbbbbbbbbbbk........",
        "........kLLLLbbbbbbbbbbk........",
        ".......kLLLLLLbbbbbbbbbbk.......",
        ".......kLLLLLLLbbbbbbbbbk.......",
        "......kbLLLLLLLLbbbbbbbbnk......",
        "......kbbLLLLLLGbbbbbGbbnk......",
        "......kbbbLbLLGGGbbbbGGGnk......",
        "......kbbbbbbGGGGbbbbbGGnk......",
        "......kbbbbbbbbGGGbbbbGGGk......",
        "......kbbbbbbbbbGGbbbbGGGk......",
        ".......kbbbbbbbbbbbbbnnnk.......",
        ".......kbbbbbbbbbbbbnnnnk.......",
        "........kbbbbbbbbbnnnnnk........",
        ".....k..kGbbbbbbbnnnnnnk........",
        "...okyk..kkbbbbnnnnnnkk.........",
        "...kywyk...kknnnnnnkk...........",
        "....kyk......kkkkkk.............",
        ".....k..........................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
    ])

    static let logo6 = PixelArt([
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        ".............kkkkkk.............",
        "...........kkbbbbbbkk...........",
        ".........kkccbbbbbbbbkk.........",
        "........kcLLLLLbbbbbbbbk........",
        "........kcLLLLLLbbbbbbbk........",
        ".......kLcLLLLLLLbbbbbbbk.......",
        ".......kLcLLLLLLLGbbbbbbk.......",
        "......kbbbLLLLLLGGGbbbbGnk......",
        "......kbbbbLLLLGGGGbbbbGGk......",
        "......kbbbbbbbbGGGGbbbbGGk......",
        "......kbbbbbbbbbbGGGbbbGGk......",
        "......kbbbbbbbbbbbbGbbnnGk......",
        "......kbbbbbbbbbbbbbbbnnnk......",
        ".......kbbbbbbbbbbbbbnnnk.......",
        ".......kGbbbbbbbbbbbnnnnk.......",
        "........kGbbbbkbbbnnnnnk........",
        "........kGGGbkykbnnnnnnk........",
        ".........kkGkywyknnnnkk.........",
        "..........oyykyknnnkk...........",
        ".........o...kkkkkk.............",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
    ])

    static let logo7 = PixelArt([
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        ".............kkkkkk.............",
        "...........kkbbbbbbkk...........",
        ".........kkccLbbbbbbbkk.........",
        "........kccLLLLLLbbbbbbk........",
        "........kccLLLLLLLGbbbbk........",
        ".......kcLccLLLLLGGGbbbbk.......",
        ".......kbLcbLLLLLGGGGbbbk.......",
        "......kbbbbbbLLLGGGGGbbbGk......",
        "......kbbbbbbbbbbGGGGGbbnk......",
        "......kbbbbbbbbbbbbGGbbbnk......",
        "......kbbbbbbbbbbbbbbGbknk......",
        "......kbbbbbbbbbbbbbbbkykk......",
        "......kbbbbbbbbbbbbbbkywyk......",
        ".......kGGbbbbbbbbbbbykyk.......",
        ".......kbGGGbbbbbbboonnkk.......",
        "........kGGGGbbbbbonnnnk........",
        "........kbGGGGbbbnnnnnnk........",
        ".........kkbbbbnnnnnnkk.........",
        "...........kknnnnnnkk...........",
        ".............kkkkkk.............",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
        "................................",
    ])
}
